---
- name: systemctl restart controller service
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  loop: "{{ os_controller_service_name }}"
...
